### ISSUE TITLE
Make Error

### ISSUE THREAD

**Issue by charlesbel** [TomAbel/evilginx.botguard#5]
Hi Tom,
I am checking your project that seems incredible, but when I run `make` on your project I get this error :
core/botguard.go:12:2: cannot find package "." in:
        /home/kali/evilginx.botguard/vendor/github.com/go-rod/rod
core/botguard.go:13:2: cannot find package "." in:
        /home/kali/evilginx.botguard/vendor/github.com/go-rod/rod/lib/input
main.go:11:2: cannot find package "." in:
        /home/kali/evilginx.botguard/vendor/github.com/go-rod/rod/lib/launcher
core/botguard.go:15:2: cannot find package "." in:
        /home/kali/evilginx.botguard/vendor/github.com/go-rod/rod/lib/proto
core/botguard.go:16:2: cannot find package "." in:
        /home/kali/evilginx.botguard/vendor/github.com/go-rod/stealth
make: *** [Makefile:8 : build] Error 1

I tried many things to install go-rod, but I still get this error. Would you be enough kind to help me ?

**Comment by TomAbel** [comment]
This is because I have included a vendor folder from the original repository but it doesn't contain the go-rod package which I added.
run either `go mod vendor` or `go mod tidy`

**Comment by charlesbel** [comment]
That's awesome dude ! Greate Job !
