### ISSUE TITLE
CORS Errors 

### ISSUE THREAD

**Issue by ssl-user-en** [TomAbel/evilginx.botguard#6]
#### REPORT ONLY BUGS OR FEATURE SUGGESTIONS.

So these are the new errors i'm getting which could be a problem which is not letting me go to the next page.

![image](https://user-images.githubusercontent.com/85633615/132635763-163a9055-4e9d-4559-b8e5-9232eeaeb385.png)

**Comment by TomAbel** [comment]
I see you got it working, closing this.
